import {
  BrandInterface,
  ProductInterface,
  QuestionInterface,
  ReviewInterface,
  NewsInterface,
  PaymentMethodInterface,
  CustomerDetailInterface,
} from "./types";
const brands: BrandInterface[] = [
  {
    id: 1,
    imgSrc: "asap.jpeg",
    price: 1.99,
    name: "ASAP",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: ["ONE REPLACEMENT IN CASE CANCELLED / DECLINED"],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 2,
    imgSrc: "bite-squad.jpeg",
    price: 1.5,
    name: "Bite Squad",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: ["ONE REPLACEMENT IN CASE CANCELLED / DECLINED"],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 3,
    imgSrc: "cafe-rio.jpeg",
    price: 1.5,
    name: "Cafe Rio",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 48-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 4,
    imgSrc: "carter's.jpeg",
    price: 1.99,
    name: "Carters's",
    categoryId: [2],
    inStock: true,
    productType: "",
    description: [
      "There is a 48-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 5,
    imgSrc: "casey's.jpeg",
    price: 2.99,
    name: "Casey's",
    categoryId: [3],
    inStock: true,
    productType: "",
    description: [
      "There is a 48-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Rewards:",
      "250 Points = $1.00 Casey's Cash OR 0.05c off / gallon.",
      "5000 Points = +$1.00 off / gallon. Up to 20 gallons.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 6,
    imgSrc: "chicken-salad-chick.jpeg",
    price: 0.99,
    name: "Chicken Salad Chick",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      " ",
      "Warranty covers wrong reward balances and invalid accounts.",
      " ",
      "Rewards menu:",
      " ",
      "Free Coozie - 25 Points",
      "Free Large Drink - 50 Points",
      "Free Buttercream Frosted Cookie - 50 Points",
      "Free Side Item - 75 Points",
      "Free Bowl of Soup - 100 Points",
      "$5 Off Purchase - 100 Points",
      "Free Small Cooler - 125 Points",
      "Free Scoop or Sandwich - 125 Points",
      "Free Large Quick Chick - 150 Points",
      "Free Chocolate Crispy Bites Tray - 200 Points",
      "$10 Off Purchase - 200 Points",
      "Chick T Shirt - 200 Points",
      "Free Gallon of Iced Tea - 200 Points",
      "Free Buttercream Cookie Tray - 200 Points",
      "Free Gallon of Lemonade - 200 Points",
      "Chick Tervis Tumbler - 250 Points",
      "Free Large Cooler - 250 Points",
      "$25 Off Purchase - 400 Points",
      " ",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 7,
    imgSrc: "city-brew-coffee.png",
    price: 0.49,
    name: "City Brew Coffee",
    categoryId: [4, 1],
    inStock: true,
    productType: "gift cards",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong balances or issues when going in-store.",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 8,
    imgSrc: "del-taco.jpeg",
    price: 0.99,
    name: "Del Taco",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong reward balances and invalid accounts.",

      "Rewards menu:",

      "Breakfast Toasted Wrap - 250 Points",
      "Add 2 Scoops of Guac to Anything - 250 Points",
      "Grilled Chicken Taco - 300 Points",
      "Bean and Cheese Burrito - 300 Points",
      "Any 20 Under $2 Menu Item - 300 Points",
      "Small Fountain Drink - 350 Points",
      "The Del Taco - 350 Points",
      "Medium Crinkle Cut Fries - 450 Points",
      "Snack Size Chips and Guac - 450 Points",
      "Snack Size Chips and Queso - 450 Points",
      "Beyond Taco - 500 Points",
      "Breakfast Burrito - 600 Points",
      "Regular Size Shake - 600 Points",
      "Epic Burrito - 1000 Points",
      "Beyond 8 Layer Burrito - 1000 Points",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 9,
    imgSrc: "dickey's-barbeque-pit.jpeg",
    price: 0.5,
    name: "Dickey's Barbeque Pit",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Rewards can be used between ALL of their brands - Dickey&apos;s Barbecue Pit, Big Deal Burger, Trailer Birds and Wing Boss. You will have to sign onto the respective app to redeem.",

      "Rewards menu:",

      "Big Yellow Cup - 250 Points",
      "Chocolate Cookie - 300 Points",
      "Blondie Brownie - 300 Points",
      "Pecan Pie - 300 Points",
      "Beef Brisket Classic Sandwich - 700 Points",
      "Pulled Pork Classic Sandwich - 700 Points",
      "Westerner Sandwich - 850 Points",
      "1 Meat Plate - 1250 Points",
      "2 Meat Plate - 1350 Points",
      "3 Meat Plate - 1450 Points",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 10,
    imgSrc: "einstein-bros.jpeg",
    price: 0.75,
    name: "Einstein Bros. Bagels",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong reward balances and invalid accounts.",

      "Rewards menu:",

      "Free Beverage Size Upgrade - 30 Points",
      "Free Whip, Flavor Shot or Espresso Shot - 30 Points",
      "Free Any Size Brewed Coffee - 75 Points",
      "Free Any Bakery Item - 75 Points",
      "Free Bagel & Shmear - 100 Points",
      "Free Any Beverage, Any Size - 120 Points",
      "Free Any Egg Sandwich - 185 Points",
      "Free Half Dozen (6 Bagels Only) - 225 Points",
      "Free Baker's Dozen (13 Bagels Only) - 375 Points",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 11,
    imgSrc: "erbert-n-gerbert's.jpeg",
    price: 1.5,
    name: "Erbert & Herbert's",
    categoryId: [1, 4],
    inStock: true,
    productType: "gift cards",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong balances or issues when going in-store.",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 12,
    imgSrc: "firehouse-subs.jpeg",
    price: 1.5,
    name: "Firehouse Subs",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 13,
    imgSrc: "freddy's.jpeg",
    price: 0.99,
    name: "Freddy's",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 6-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 14,
    imgSrc: "gtc.jpeg",
    price: 1.99,
    name: "GTC Movies",
    categoryId: [5],
    inStock: true,
    productType: "",
    description: [
      "There is a 6-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong reward balances and invalid accounts.",

      "Rewards menu:",

      "Any Candy - 700 Points",
      "Medium Popcorn & Large Drink, or any one size Popcorn, or Fountain Drink - 1000 Points",
      "Combo #2 (Medium Popcorn, Large Drink & Candy) - 1500 Points",
      "Ticket - 2000 Points",
      "3D, GTX, LX Ticket - 2500 Points",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 15,
    imgSrc: "hot-topic.jpeg",
    price: 0.75,
    name: "Hot Topic",
    categoryId: [2],
    inStock: true,
    productType: "",
    description: [
      "There is a 48-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong reward balances and invalid accounts.",

      "Its not possible to stack rewards from multiple accounts. You can only use 1 account per transaction!",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 16,
    imgSrc: "ihop.jpeg",
    price: 0.99,
    name: "IHOP",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 17,
    imgSrc: "instacart.jpeg",
    price: 1.5,
    name: "Instacart",
    categoryId: [2],
    inStock: true,
    productType: "",
    description: ["ONE REPLACEMENT IN CASE CANCELLED / DECLINED"],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 18,
    imgSrc: "jane.jpeg",
    price: 1.5,
    name: "Jane",
    categoryId: [2],
    inStock: true,
    productType: "",
    description: ["ONE REPLACEMENT IN CASE CANCELLED / DECLINED"],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 19,
    imgSrc: "krispy-kreme.jpeg",
    price: 1.5,
    name: "Krispy Kreme",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 20,
    imgSrc: "kum-n-go.jpeg",
    price: 2.99,
    name: "Kum & Go",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: ["ONE REPLACEMENT IN CASE CANCELLED / DECLINED"],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 21,
    imgSrc: "loves.jpeg",
    price: 1.99,
    name: "Love's",
    categoryId: [3],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong reward balances and invalid accounts.",

      "Every 1000 points equal $10. Points can be used in-store for anything except gas. That includes, food and the restaurants connected with the Love's location (excluding alcohol and fuel).",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 22,
    imgSrc: "marcus-theatres.jpeg",
    price: 1.99,
    name: "Marcus Theatres",
    categoryId: [4, 5],
    inStock: true,
    productType: "gift cards",
    description: [
      "There is a 6-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "THESE CAN BE STACKED",

      "Warranty covers wrong reward balances.",

      "You will receive Gift Card + PIN",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 23,
    imgSrc: "meijer.jpeg",
    price: 2.99,
    name: "Meijer",
    categoryId: [1],
    inStock: true,
    productType: "points",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "1000 Points = $1.00",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 24,
    imgSrc: "mountain-hike's-pizza.jpeg",
    price: 1.99,
    name: "Mountain Mike's Pizza",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: ["ONE REPLACEMENT IN CASE CANCELLED / DECLINED"],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 25,
    imgSrc: "nando's.jpeg",
    price: 0.99,
    name: "Nando's PERi-PERi",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong reward balances and invalid accounts.",

      "Rewards menu:",

      "$5 Off - 500 Points",
      "$10 Off - 1000 Points",
      "$15 Off - 1500 Points",
      "$25 Off - 2500 Points",
      "$50 Off - 5000 Points",
      "$100 Off - 10000 Points",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 26,
    imgSrc: "noodles-n-company.jpeg",
    price: 0.99,
    name: "Noodles & Company",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 72-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong reward balances and invalid accounts.",

      "Rewards menu:",

      "Side Salad or Mac - 300 Points",
      "Regular Fountain Drink - 300 Points",
      "Side Soup - 350 Points",
      "Dessert (Crispy or Cookie) - 350 Points",
      "Protein Addon - 575 Points",
      "Small Shareable - 600 Points",
      "Regular Shareable - 850 Points",
      "Small Entree - 1150 Points",
      "Regular Entree - 1500 Points",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 27,
    imgSrc: "n-pizza.jpeg",
    price: 0.99,
    name: "&pizza",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong reward balances and invalid accounts.",

      "One Reward Per Transaction",

      "Rewards menu:",

      "$1 Off - 100 Points",
      "Free Soda - 250 Points",
      "$5 Off - 500 Points",
      "Free Pizza - 1500 Points",
      "10 Pies & 10 Sodas Free - 10,000 Points",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 28,
    imgSrc: "o'reilly-auto-parts.jpeg",
    price: 0.5,
    name: "O'Reilly Auto Parts",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers issues with redeeming the coupon or expired coupons.",

      "These are not stackable.",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 29,
    imgSrc: "pilot-flying.jpeg",
    price: 1.5,
    name: "Pilot Flying J",
    categoryId: [3],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong reward balances and invalid accounts.",

      "Every 1000 points equal $10. Points can be used in-store for anything except gas. That includes, food and the restaurants connected with the Pilot location (excluding alcohol, lottery and tobacco).",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 30,
    imgSrc: "potbelly-sandwich-shop.jpeg",
    price: 1.99,
    name: "Potbelly Sandwich Shop",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: ["ONE REPLACEMENT IN CASE CANCELLED / DECLINED"],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 31,
    imgSrc: "pressed-juicery.jpeg",
    price: 2.5,
    name: "Pressed Juicery",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong reward balances and invalid accounts.",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 32,
    imgSrc: "restaurant.jpeg",
    price: 1.5,
    name: "Restaurant.com",
    categoryId: [1, 4],
    inStock: true,
    productType: "gift cards",
    description: [
      "There is a 48-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers invalid gift cards, or errors while adding it.",

      "These gift cards offer discounts at your local restaurants. Example, you'd get $50 off a $100 purchase at a local participating restaurant. Do not buy under the impression you get to use this gift card fully for the cost of a restaurant. ",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 33,
    imgSrc: "round-table.jpeg",
    price: 0.99,
    name: "Round Table Pizza",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 34,
    imgSrc: "rubio's.jpeg",
    price: 0.99,
    name: "Rubio's Coastal Grill",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong reward balances and invalid accounts.",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 35,
    imgSrc: "safeway.jpeg",
    price: 0.5,
    name: "Safeway",
    categoryId: [3],
    inStock: true,
    productType: "",
    description: [
      "There is a 48-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong reward balances and invalid accounts.",

      "1 Point= $0.10 Off Per Gal At Participating Gas Stations. Up To $1.00 Per Gal Off. Find participating locations here: https://local.safeway.com/search.html",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 36,
    imgSrc: "salad-n-go.jpeg",
    price: 2.99,
    name: "Salad and Go",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",

      "Warranty covers wrong reward balances and invalid accounts.",

      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 37,
    imgSrc: "smoothie-king.jpeg",
    price: 1.99,
    name: "Smoothie King",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: ["ONE REPLACEMENT IN CASE CANCELLED / DECLINED"],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 42,
    imgSrc: "sonic.jpeg",
    price: 1.5,
    name: "Sonic Drive-In",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: ["ONE REPLACEMENT IN CASE CANCELLED / DECLINED"],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 38,
    imgSrc: "the-human-bean.jpeg",
    price: 1.99,
    name: "The Human Bean",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: ["ONE REPLACEMENT IN CASE CANCELLED / DECLINED"],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 39,
    imgSrc: "under-armour.jpeg",
    price: 0.99,
    name: "Under Armour",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: ["ONE REPLACEMENT IN CASE CANCELLED / DECLINED"],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 40,
    imgSrc: "wendy's.jpeg",
    price: 0.25,
    name: "Wendy's",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
  {
    id: 41,
    imgSrc: "zaxby's.jpeg",
    price: 0.45,
    name: "Zaxby's",
    categoryId: [1],
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
    stars: 5,
    sold: 11,
    reviews: 8,
  },
];

const products: ProductInterface[] = [
  { label: "[$5 - $9.99]", price: 1.5, brandId: 19, stock: 123, id: 1 },
  { label: "[$10 - $14.99]", price: 2.5, brandId: 19, stock: 44, id: 2 },
  { label: "[$15 - $19.99]", price: 3.99, brandId: 19, stock: 5, id: 3 },
  { label: "[$20 - $24.99]", price: 5.5, brandId: 19, stock: 0, id: 4 },
  { label: "[$25 - $29.99]", price: 6.99, brandId: 19, stock: 0, id: 5 },
  { label: "[$30 - $39.99]", price: 9.99, brandId: 19, stock: 0, id: 6 },
  { label: "[$40 - $49.99]", price: 12.99, brandId: 19, stock: 1, id: 7 },
  { label: "[150-299 Points]", price: 0.25, brandId: 40, stock: 152, id: 8 },
  { label: "[300-449 Points]", price: 0.75, brandId: 40, stock: 125, id: 9 },
  { label: "[450-599 Points]", price: 1.25, brandId: 40, stock: 70, id: 10 },
  { label: "[600-799 Points]", price: 1.99, brandId: 40, stock: 42, id: 11 },
  { label: "[800-999 Points]", price: 2.99, brandId: 40, stock: 14, id: 12 },
  { label: "[1000-1499 Points]", price: 3.99, brandId: 40, stock: 3, id: 13 },
  { label: "[1500-1999 Points]", price: 6.99, brandId: 40, stock: 0, id: 14 },
  { label: "[2000-2499 Points]", price: 9.99, brandId: 40, stock: 1, id: 15 },
  { label: "[2500-2999 Points]", price: 12.99, brandId: 40, stock: 0, id: 16 },
  { label: "[3000-4999 Points]", price: 15.99, brandId: 40, stock: 3, id: 17 },
  { label: "[5000+ Points]", price: 22.99, brandId: 40, stock: 1, id: 18 },
  { label: "[6000+ Points]", price: 25.99, brandId: 40, stock: 0, id: 19 },
  { label: "[7000+ Points]", price: 29.99, brandId: 40, stock: 0, id: 20 },
  {
    label: "[price: 10 - 14.99 Balance]",
    price: 4.99,
    brandId: 40,
    stock: 0,
    id: 21,
  },
  { label: "[price: 25 Balance]", price: 7.99, brandId: 40, stock: 0, id: 22 },
  {
    label: "[price: 45 - 49.99 Balance]",
    price: 16.99,
    brandId: 40,
    stock: 0,
    id: 23,
  },
  {
    label: "[price: 55 - 59.99 Balance]",
    price: 19.99,
    brandId: 40,
    stock: 0,
    id: 24,
  },
  { label: "[Payment Attached]", price: 1.5, brandId: 42, stock: 41, id: 25 },
  { label: "[AMEX / DIS]", price: 3.5, brandId: 42, stock: 0, id: 26 },
  {
    label: "[6,000 - 9,999 Points]",
    price: 1.5,
    brandId: 12,
    stock: 463,
    id: 27,
  },
  {
    label: "[10,000 - 19,999 Points]",
    price: 4.5,
    brandId: 12,
    stock: 614,
    id: 28,
  },
  {
    label: "[20,000 - 29,999 Points]",
    price: 7.5,
    brandId: 12,
    stock: 61,
    id: 29,
  },
  {
    label: "[30,000 - 39,999 Points]",
    price: 9.99,
    brandId: 12,
    stock: 15,
    id: 30,
  },
  {
    label: "[40,000 - 49,999 Points]",
    price: 12.5,
    brandId: 12,
    stock: 7,
    id: 31,
  },
  {
    label: "[50,000 - 74,999 Points]",
    price: 20.99,
    brandId: 12,
    stock: 9,
    id: 32,
  },
  {
    label: "[75,000 - 99,999 Points]",
    price: 26.99,
    brandId: 12,
    stock: 2,
    id: 33,
  },
  {
    label: "[100,000 - 149,999 Points]",
    price: 34.99,
    brandId: 12,
    stock: 3,
    id: 34,
  },
  {
    label: "[200,000 - 299,999 Points]",
    price: 74.99,
    brandId: 12,
    stock: 1,
    id: 35,
  },
  { label: "[50+ Points]", price: 0.99, brandId: 33, stock: 1, id: 36 },
  { label: "[75+ Points]", price: 2.5, brandId: 33, stock: 1, id: 37 },
  { label: "[100+ Points]", price: 4.99, brandId: 33, stock: 1, id: 38 },
  { label: "[125+ Points]", price: 5.99, brandId: 33, stock: 2, id: 39 },
  { label: "[150+ Points]", price: 8.99, brandId: 33, stock: 0, id: 40 },
  { label: "[200+ Points]", price: 11.99, brandId: 33, stock: 0, id: 41 },
  { label: "[250+ Points]", price: 13.99, brandId: 33, stock: 2, id: 42 },
  { label: "[350+ Points]", price: 19.99, brandId: 33, stock: 0, id: 43 },
  { label: "[400+ Points]", price: 22.99, brandId: 33, stock: 1, id: 44 },
  { label: "[800+ Points]", price: 39.99, brandId: 33, stock: 1, id: 45 },
  { label: "[Payment Attached]", price: 1.5, brandId: 17, stock: 210, id: 46 },
  { label: "[AMEX / DIS]", price: 2.99, brandId: 17, stock: 29, id: 47 },
  { label: "[PayPal]", price: 3.99, brandId: 17, stock: 0, id: 48 },
  {
    label: "[$30+ Gift Card Balance]",
    price: 9.99,
    brandId: 17,
    stock: 0,
    id: 49,
  },
  {
    label: "[$89+ Gift Card Balance]",
    price: 28.99,
    brandId: 17,
    stock: 0,
    id: 50,
  },
  { label: "[$10+]", price: 2.99, brandId: 23, stock: 1560, id: 51 },
  { label: "[$20+]", price: 5.99, brandId: 23, stock: 527, id: 52 },
  { label: "[$30+]", price: 8.99, brandId: 23, stock: 141, id: 53 },
  { label: "[$40+]", price: 11.99, brandId: 23, stock: 0, id: 54 },
  { label: "[$50+]", price: 14.99, brandId: 23, stock: 0, id: 55 },
  { label: "[$60+]", price: 17.99, brandId: 23, stock: 0, id: 56 },
  { label: "[$70+]", price: 20.99, brandId: 23, stock: 0, id: 57 },
  { label: "[$80+]", price: 23.99, brandId: 23, stock: 0, id: 58 },
  { label: "[$90+]", price: 26.99, brandId: 23, stock: 0, id: 59 },
  { label: "[$100+]", price: 29.99, brandId: 23, stock: 0, id: 60 },
  { label: "[250+ Points]", price: 0.45, brandId: 41, stock: 29, id: 61 },
  { label: "[700+ Points]", price: 1.5, brandId: 41, stock: 1, id: 62 },
  { label: "[1050+ Points]", price: 1.99, brandId: 41, stock: 0, id: 63 },
  {
    label: "[$5 - $9.99 Gift Card Balance]",
    price: 1.5,
    brandId: 41,
    stock: 1,
    id: 64,
  },
  {
    label: "[$10+ Gift Card Balance]",
    price: 1.99,
    brandId: 41,
    stock: 0,
    id: 65,
  },
  {
    label: "[$15+ Gift Card Balance]",
    price: 2.99,
    brandId: 41,
    stock: 0,
    id: 66,
  },
  { label: "[Payment Attached]", price: 1.99, brandId: 41, stock: 36, id: 67 },
  { label: "[AMEX / DIS]", price: 3.5, brandId: 41, stock: 0, id: 68 },
  { label: "[10+ Points]", price: 0.99, brandId: 16, stock: 676, id: 69 },
  { label: "[15+ Points]", price: 2.99, brandId: 16, stock: 220, id: 70 },
  { label: "[20+ Points]", price: 4.99, brandId: 16, stock: 48, id: 71 },
  { label: "[25+ Points]", price: 6.5, brandId: 16, stock: 16, id: 72 },
  { label: "[30+ Points]", price: 7.99, brandId: 16, stock: 9, id: 73 },
  { label: "[40+ Points]", price: 9.99, brandId: 16, stock: 2, id: 74 },
  { label: "[50+ Points]", price: 14.99, brandId: 16, stock: 0, id: 75 },
  { label: "[70+ Points]", price: 19.99, brandId: 16, stock: 0, id: 76 },
  { label: "[500 - 999 Points]", price: 0.5, brandId: 9, stock: 50, id: 77 },
  { label: "[1000 - 1349 Points]", price: 1.5, brandId: 9, stock: 10, id: 78 },
  { label: "[1350 - 1999 Points]", price: 2.99, brandId: 9, stock: 6, id: 79 },
  { label: "[2000 - 2999 Points]", price: 3.99, brandId: 9, stock: 0, id: 80 },
  { label: "[3000 - 3999 Points]", price: 4.99, brandId: 9, stock: 0, id: 81 },
  { label: "[4000 - 5999 Points]", price: 5.99, brandId: 9, stock: 0, id: 82 },
  { label: "[6000 - 9999 Points]", price: 6.99, brandId: 9, stock: 0, id: 83 },
  { label: "[Payment Attached]", price: 1.99, brandId: 1, stock: 122, id: 84 },
  { label: "[AMEX / DIS]", price: 3.5, brandId: 1, stock: 1, id: 85 },
  { label: "[Payment Attached]", price: 1.99, brandId: 2, stock: 433, id: 86 },
  { label: "[AMEX / DIS]", price: 3.5, brandId: 2, stock: 58, id: 87 },
  { label: "[3+ Rewards]", price: 0.5, brandId: 35, stock: 1071, id: 88 },
  { label: "[5+ Rewards]", price: 0.99, brandId: 35, stock: 362, id: 89 },
  { label: "[7+ Rewards]", price: 1.8, brandId: 35, stock: 260, id: 90 },
  { label: "[10+ Rewards]", price: 2.5, brandId: 35, stock: 34, id: 91 },
  { label: "[12+ Rewards]", price: 4.2, brandId: 35, stock: 23, id: 92 },
  { label: "[20+ Rewards]", price: 7.99, brandId: 35, stock: 1, id: 93 },
  { label: "[400+ Points]", price: 0.99, brandId: 34, stock: 46, id: 94 },
  { label: "[700+ Points]", price: 2.99, brandId: 34, stock: 90, id: 95 },
  { label: "[1300+ Points]", price: 5.99, brandId: 34, stock: 0, id: 96 },
  { label: "[Payment Attached]", price: 1.99, brandId: 34, stock: 679, id: 97 },
  { label: "[AMEX / DIS]", price: 3.5, brandId: 34, stock: 53, id: 98 },
  { label: "[100 - 119 Points]", price: 0.75, brandId: 10, stock: 21, id: 99 },
  { label: "[120 - 184 Points]", price: 0.99, brandId: 10, stock: 28, id: 100 },
  { label: "[185 - 224 Points]", price: 1.25, brandId: 10, stock: 10, id: 101 },
  { label: "[225 - 299 Points]", price: 1.99, brandId: 10, stock: 12, id: 102 },
  { label: "[300 - 374 Points]", price: 2.5, brandId: 10, stock: 5, id: 103 },
  { label: "[375 - 500 Points]", price: 3.5, brandId: 10, stock: 2, id: 104 },
  { label: "[501+ Points]", price: 4.5, brandId: 10, stock: 4, id: 105 },
  {
    label: "[$5 - $9.99 Bank Rewards]",
    price: 1.25,
    brandId: 10,
    stock: 6,
    id: 106,
  },
  {
    label: "[$10 - $14.99 Bank Rewards]",
    price: 1.99,
    brandId: 10,
    stock: 0,
    id: 107,
  },
  {
    label: "[$15- $19.99 Bank Rewards]",
    price: 2.99,
    brandId: 10,
    stock: 0,
    id: 108,
  },
  { label: "[$20+ Bank Rewards]", price: 4.99, brandId: 10, stock: 2, id: 109 },
  { label: "[$30+ Bank Rewards]", price: 5.99, brandId: 10, stock: 2, id: 110 },
  { label: "[$60 Bank Rewards]", price: 11.99, brandId: 10, stock: 1, id: 111 },
  { label: "[1500+ Points]", price: 9.99, brandId: 10, stock: 1, id: 112 },
  { label: "[300+ Points]", price: 0.99, brandId: 26, stock: 633, id: 113 },
  { label: "[600+ Points]", price: 1.5, brandId: 26, stock: 263, id: 114 },
  { label: "[850+ Points]", price: 1.99, brandId: 26, stock: 142, id: 115 },
  { label: "[1150+ Points]", price: 2.5, brandId: 26, stock: 148, id: 116 },
  { label: "[1500+ Points]", price: 2.99, brandId: 26, stock: 89, id: 117 },
  { label: "[3000+ Points]", price: 5.99, brandId: 26, stock: 16, id: 118 },
  { label: "[4500+ Points]", price: 8.99, brandId: 26, stock: 6, id: 119 },
  { label: "[6000+ Points]", price: 11.99, brandId: 26, stock: 3, id: 120 },
  { label: "[7500+ Points]", price: 14.99, brandId: 26, stock: 0, id: 121 },
  { label: "[15,500+ Points]", price: 29.99, brandId: 26, stock: 0, id: 122 },
  { label: "[+33,000 Points]", price: 64.99, brandId: 26, stock: 1, id: 123 },
  { label: "[250 - 449 Points]", price: 0.99, brandId: 8, stock: 23, id: 124 },
  { label: "[450 - 599 Points]", price: 1.99, brandId: 8, stock: 5, id: 125 },
  { label: "[600 - 999 Points]", price: 2.99, brandId: 8, stock: 10, id: 126 },
  { label: "[1000 - 1499 Points]", price: 4.5, brandId: 8, stock: 5, id: 127 },
  { label: "[1500 - 1999 Points]", price: 5.99, brandId: 8, stock: 1, id: 128 },
  { label: "[2000+ Points]", price: 7.99, brandId: 8, stock: 2, id: 129 },
  { label: "[3000+ Points]", price: 9.99, brandId: 8, stock: 0, id: 130 },
  { label: "[4000+ Points]", price: 11.99, brandId: 8, stock: 0, id: 131 },
  { label: "[$10+] (Gift Card)", price: 1.5, brandId: 3, stock: 18, id: 132 },
  { label: "[$20+] (Gift Card)", price: 3.99, brandId: 3, stock: 34, id: 133 },
  { label: "[$30+] (Gift Card)", price: 5.99, brandId: 3, stock: 0, id: 134 },
  {
    label: "[$70-80] (Gift Card)",
    price: 15.99,
    brandId: 3,
    stock: 2,
    id: 135,
  },
  {
    label: "[+$100] (Gift Cards)",
    price: 20.99,
    brandId: 3,
    stock: 1,
    id: 136,
  },
  { label: "[$10 - $14.99]", price: 1.99, brandId: 3, stock: 1753, id: 137 },
  { label: "[$15 - $19.99]", price: 2.5, brandId: 3, stock: 33, id: 138 },
  { label: "[$20 - $29.99]", price: 3.99, brandId: 3, stock: 282, id: 139 },
  { label: "[$30 - $39.99]", price: 5.99, brandId: 3, stock: 87, id: 140 },
  { label: "[$40 - $49.99]", price: 7.99, brandId: 3, stock: 35, id: 141 },
  { label: "[$70 - $79.99]", price: 13.99, brandId: 3, stock: 7, id: 142 },
  { label: "[$100-$125]", price: 19.99, brandId: 3, stock: 11, id: 143 },
  { label: "[$179+]", price: 35.99, brandId: 3, stock: 1, id: 144 },
  {
    label: "[+$278] (Gift Card) + $50 Rewards",
    price: 64.99,
    brandId: 3,
    stock: 1,
    id: 145,
  },
  { label: "[$462+]", price: 89.99, brandId: 3, stock: 1, id: 146 },
  { label: "[+$140]", price: 26.99, brandId: 3, stock: 1, id: 147 },
  { label: "[$160-$170]", price: 30.99, brandId: 3, stock: 2, id: 148 },
  { label: "[$190-$200]", price: 36.99, brandId: 3, stock: 3, id: 149 },
  { label: "[$219-$249]", price: 44.5, brandId: 3, stock: 2, id: 150 },
  { label: "[$250-$275]", price: 49.99, brandId: 3, stock: 3, id: 151 },
  { label: "[+$200] (Gift Card)", price: 37.99, brandId: 3, stock: 0, id: 152 },
  { label: "[$+620]", price: 99.99, brandId: 3, stock: 1, id: 153 },
  { label: "[Payment Attached]", price: 1.99, brandId: 24, stock: 63, id: 154 },
  { label: "[AMEX / DIS]", price: 3.5, brandId: 24, stock: 8, id: 155 },
  { label: "[Payment Attached]", price: 1.99, brandId: 30, stock: 55, id: 156 },
  { label: "[AMEX / DIS]", price: 3.5, brandId: 30, stock: 22, id: 157 },
  {
    label: "[500 - 1499 Points]",
    price: 0.99,
    brandId: 27,
    stock: 187,
    id: 158,
  },
  { label: "[1500+ Points]", price: 1.5, brandId: 27, stock: 8, id: 159 },
  { label: "[2000+ Points]", price: 2.99, brandId: 27, stock: 5, id: 160 },
  { label: "[3000+ Points]", price: 4.5, brandId: 27, stock: 4, id: 161 },
  { label: "[4000+ Points]", price: 5.99, brandId: 27, stock: 0, id: 162 },
  { label: "[5000+ Points]", price: 7.5, brandId: 27, stock: 0, id: 163 },
  { label: "[500+ Points]", brandId: 25, price: 0.99, stock: 33, id: 164 },
  { label: "[1000+ Points]", brandId: 25, price: 2.5, stock: 22, id: 165 },
  { label: "[1500+ Points]", brandId: 25, price: 3.99, stock: 20, id: 166 },
  { label: "[2500+ Points]", brandId: 25, price: 7.5, stock: 13, id: 167 },
  {
    label: "[5000 - 7499 Points]",
    brandId: 25,
    price: 19.99,
    stock: 3,
    id: 168,
  },
  {
    label: "[7500 - 9999 Points]",
    brandId: 25,
    price: 24.99,
    stock: 1,
    id: 169,
  },
  { label: "[$10 - $14.99]", brandId: 31, price: 2.5, stock: 25, id: 170 },
  { label: "[$20 - $29.99]", brandId: 31, price: 4.99, stock: 8, id: 171 },
  { label: "[$50 - $74.99]", brandId: 31, price: 11.99, stock: 3, id: 172 },
  { label: "[$75 - $99.99]", brandId: 31, price: 16.99, stock: 3, id: 173 },
  { label: "[$100 - $129]", brandId: 31, price: 21.99, stock: 3, id: 174 },
  { label: "[$130-$149]", brandId: 31, price: 30.99, stock: 2, id: 175 },
  { label: "[$150-$200]", brandId: 31, price: 38.99, stock: 2, id: 176 },
  { label: "[$200+]", brandId: 31, price: 64.99, stock: 4, id: 177 },
  { label: "[$250+]", brandId: 31, price: 79.99, stock: 2, id: 178 },
  { label: "[$300+]", brandId: 31, price: 99.99, stock: 1, id: 179 },
  { label: "[300+ Points]", brandId: 13, price: 0.99, stock: 5, id: 180 },
  { label: "[700+ Points]", brandId: 13, price: 1.99, stock: 0, id: 181 },
  { label: "[1000+ Points]", brandId: 13, price: 2.99, stock: 0, id: 182 },
  { label: "[4500+ Points]", brandId: 13, price: 13.5, stock: 0, id: 183 },
  { label: "[Payment Attached]", brandId: 37, price: 1.99, stock: 44, id: 184 },
  { label: "[AMEX / DIS]", brandId: 37, price: 3.5, stock: 2, id: 185 },
  { label: "[$10 - $14.99]", brandId: 36, price: 2.99, stock: 0, id: 186 },
  { label: "[$15 - $19.99]", brandId: 36, price: 4.5, stock: 1, id: 187 },
  { label: "[$20 - $24.99]", brandId: 36, price: 5.5, stock: 1, id: 188 },
  { label: "[$25 - $29.99]", brandId: 36, price: 7.5, stock: 1, id: 189 },
  { label: "[100+ Points]", brandId: 6, price: 0.99, stock: 187, id: 190 },
  { label: "[200+ Points]", brandId: 6, price: 1.99, stock: 86, id: 191 },
  { label: "[400+ Points]", brandId: 6, price: 4.99, stock: 14, id: 192 },
  { label: "[600+ Points]", brandId: 6, price: 6.99, stock: 2, id: 193 },
  { label: "[800+ Points]", brandId: 6, price: 9.99, stock: 3, id: 194 },
  { label: "[1000+ Points]", brandId: 6, price: 12.99, stock: 7, id: 195 },
  { label: "[1500+ Points]", brandId: 6, price: 17.99, stock: 1, id: 196 },
  { label: "[Payment Attached]", brandId: 38, price: 1.99, stock: 8, id: 197 },
  { label: "[AMEX / DIS]", brandId: 38, price: 3.5, stock: 3, id: 198 },
  { label: "[$10 - $14.99]", brandId: 5, price: 2.99, stock: 24, id: 199 },
  { label: "[$15 - $19.99]", brandId: 5, price: 4.5, stock: 28, id: 200 },
  { label: "[$20 - $24.99]", brandId: 5, price: 5.5, stock: 0, id: 201 },
  { label: "[$25 - $29.99]", brandId: 5, price: 7.5, stock: 0, id: 202 },
  {
    label: "[1000 - 1999 Points]",
    brandId: 21,
    price: 1.99,
    stock: 0,
    id: 203,
  },
  {
    label: "[2000 - 2999 Points]",
    brandId: 21,
    price: 3.99,
    stock: 0,
    id: 204,
  },
  {
    label: "[3000 - 4999 Points]",
    brandId: 21,
    price: 6.99,
    stock: 0,
    id: 205,
  },
  {
    label: "[7000 - 9999 Points]",
    brandId: 21,
    price: 17.99,
    stock: 1,
    id: 206,
  },
  {
    label: "[10000 - 14999 Points]",
    brandId: 21,
    price: 26.99,
    stock: 2,
    id: 207,
  },
  { label: "[$5 - $9.99]", brandId: 11, price: 1.5, stock: 40, id: 208 },
  { label: "[$10 - $14.99]", brandId: 11, price: 1.99, stock: 33, id: 209 },
  { label: "[$15 - $19.99]", brandId: 11, price: 2.99, stock: 5, id: 210 },
  { label: "[$20 - $29.99]", brandId: 11, price: 4.5, stock: 10, id: 211 },
  { label: "[$30 - $39.99]", brandId: 11, price: 5.5, stock: 0, id: 212 },
  { label: "[$40 - $49.99]", brandId: 11, price: 6.99, stock: 0, id: 213 },
  { label: "[$50 - $74.99]", brandId: 11, price: 8.99, stock: 1, id: 214 },
  { label: "[$75 - $84.99]", brandId: 11, price: 11.5, stock: 1, id: 215 },
  { label: "[2000+ Points]", brandId: 14, price: 1.99, stock: 50, id: 216 },
  { label: "[4000+ Points]", brandId: 14, price: 4.99, stock: 6, id: 217 },
  { label: "[5000+ Points]", brandId: 14, price: 7.99, stock: 3, id: 218 },
  { label: "[6000+ Points]", brandId: 14, price: 9.99, stock: 0, id: 219 },
  { label: "[7000+ Points]", brandId: 14, price: 10.99, stock: 2, id: 220 },
  { label: "[8000+ Points]", brandId: 14, price: 12.99, stock: 2, id: 221 },
  { label: "[9000+ Points]", brandId: 14, price: 14.5, stock: 1, id: 222 },
  { label: "[21,000+ Points]", brandId: 14, price: 22.99, stock: 1, id: 223 },
  { label: "[$5+]", brandId: 22, price: 1.99, stock: 34, id: 224 },
  { label: "[$10+]", brandId: 22, price: 3.99, stock: 93, id: 225 },
  { label: "[$15+]", brandId: 22, price: 5.99, stock: 46, id: 226 },
  { label: "[$20+]", brandId: 22, price: 7.99, stock: 21, id: 227 },
  { label: "[$25+]", brandId: 22, price: 9.99, stock: 97, id: 228 },
  { label: "[$30+]", brandId: 22, price: 11.99, stock: 4, id: 229 },
  { label: "[$35+]", brandId: 22, price: 13.99, stock: 1, id: 230 },
  { label: "[$40+]", brandId: 22, price: 15.99, stock: 3, id: 231 },
  { label: "[$45+]", brandId: 22, price: 17.99, stock: 5, id: 232 },
  { label: "[$50+]", brandId: 22, price: 19.99, stock: 12, id: 233 },
  { label: "[$60+]", brandId: 22, price: 23.99, stock: 0, id: 234 },
  { label: "[$70+]", brandId: 22, price: 27.99, stock: 0, id: 235 },
  { label: "[$75+]", brandId: 22, price: 29.99, stock: 0, id: 236 },
  { label: "[$80+]", brandId: 22, price: 31.99, stock: 0, id: 237 },
  { label: "[$90+]", brandId: 22, price: 35.99, stock: 0, id: 238 },
  { label: "[$100+]", brandId: 22, price: 39.99, stock: 0, id: 239 },
  { label: "[$125+]", brandId: 22, price: 49.99, stock: 0, id: 240 },
  { label: "[$150+]", brandId: 22, price: 59.99, stock: 0, id: 241 },
  { label: "[$272+]", brandId: 22, price: 89.99, stock: 1, id: 242 },
  { label: "[$373+]", brandId: 22, price: 111.99, stock: 0, id: 243 },
  {
    label: "[1000 - 1999 Points]",
    brandId: 29,
    price: 1.5,
    stock: 94,
    id: 244,
  },
  {
    label: "[2000 - 2999 Points]",
    brandId: 29,
    price: 2.99,
    stock: 17,
    id: 245,
  },
  { label: "[3000 - 3999 Points]", brandId: 29, price: 4.5, stock: 2, id: 246 },
  {
    label: "[4000 - 4999 Points]",
    brandId: 29,
    price: 5.99,
    stock: 2,
    id: 247,
  },
  { label: "[5000 - 7499 Points]", brandId: 29, price: 7.5, stock: 0, id: 248 },
  {
    label: "[7500- 9999 Points]",
    brandId: 29,
    price: 14.99,
    stock: 1,
    id: 249,
  },
  {
    label: "[10,000- 14,999 Points]",
    brandId: 29,
    price: 22.99,
    stock: 2,
    id: 250,
  },
  {
    label: "[15,000- 19,999 Points]",
    brandId: 29,
    price: 39.99,
    stock: 3,
    id: 251,
  },
  { label: "[+105,000 Points]", brandId: 29, price: 274.99, stock: 0, id: 252 },
  { label: "[Payment Attached]", brandId: 18, price: 1.5, stock: 80, id: 253 },
  { label: "[AMEX / DIS]", brandId: 18, price: 3.5, stock: 8, id: 254 },
  { label: "[$10]", brandId: 4, price: 1.99, stock: 194, id: 255 },
  { label: "[$20]", brandId: 4, price: 3.99, stock: 57, id: 256 },
  { label: "[$30]", brandId: 4, price: 5.99, stock: 18, id: 257 },
  { label: "[$40]", brandId: 4, price: 7.99, stock: 7, id: 258 },
  { label: "[$50]", brandId: 4, price: 9.99, stock: 3, id: 259 },
  { label: "[$60]", brandId: 4, price: 11.99, stock: 3, id: 260 },
  { label: "[$70]", brandId: 4, price: 13.99, stock: 1, id: 261 },
  { label: "[$80]", brandId: 4, price: 15.99, stock: 0, id: 262 },
  { label: "[$5+]", brandId: 15, price: 0.75, stock: 1920, id: 263 },
  { label: "[$10+]", brandId: 15, price: 1.99, stock: 262, id: 264 },
  { label: "[$15+]", brandId: 15, price: 2.5, stock: 21, id: 265 },
  { label: "[$20+]", brandId: 15, price: 2.99, stock: 8, id: 266 },
  { label: "[$30+]", brandId: 15, price: 4.5, stock: 0, id: 267 },
  { label: "[$50]", brandId: 32, price: 1.5, stock: 3, id: 268 },
  { label: "[$100]", brandId: 32, price: 4.99, stock: 3, id: 269 },
  { label: "[$500]", brandId: 32, price: 16.99, stock: 0, id: 270 },
  { label: "[$1000]", brandId: 32, price: 29.99, stock: 1, id: 271 },
  { label: "[Payment Attached]", brandId: 39, price: 0.99, stock: 32, id: 272 },
  { label: "[AMEX / DIS]", brandId: 39, price: 2.99, stock: 1, id: 273 },
  {
    label: "[Payment Attached + No Alcohol]",
    brandId: 20,
    price: 2.99,
    stock: 0,
    id: 274,
  },
  {
    label: "[Payment Attached + Alcohol]",
    brandId: 20,
    price: 5.99,
    stock: 0,
    id: 275,
  },
  { label: "[$5 Reward Code]", brandId: 28, price: 0.5, stock: 30, id: 276 },
  { label: "[$10 Reward Code]", brandId: 28, price: 1.5, stock: 0, id: 277 },
  { label: "[$20 Reward Code]", brandId: 28, price: 3.99, stock: 0, id: 278 },
  { label: "[$30 Reward Code]", brandId: 28, price: 5.99, stock: 0, id: 279 },
  { label: "[$70 Reward Codes]", brandId: 28, price: 17.5, stock: 0, id: 280 },
  { label: "[$10 - $19.99]", brandId: 7, price: 0.49, stock: 179, id: 281 },
  { label: "[$20 - $29.99]", brandId: 7, price: 3.99, stock: 205, id: 282 },
  { label: "[$30 - $39.99]", brandId: 7, price: 6.99, stock: 10, id: 283 },
  { label: "[$40 - $49.99]", brandId: 7, price: 9.99, stock: 6, id: 284 },
  { label: "[$50 - $69.99]", brandId: 7, price: 14.99, stock: 3, id: 285 },
  { label: "[$70 - $99.99]", brandId: 7, price: 18.99, stock: 0, id: 286 },
  { label: "[$100 - $149.99]", brandId: 7, price: 23.99, stock: 1, id: 287 },
  { label: "[+$200]", brandId: 7, price: 51.99, stock: 0, id: 288 },
];

const reviews: ReviewInterface[] = [
  {
    date: "2 days ago",
    text: "Worked perfect as usual Thanks for shopping with us",
    isVerified: true,
    stars: 5,
  },
  { date: "7 days ago", isVerified: true, stars: 5 },
  { date: "7 days ago", isVerified: true, stars: 5 },
  { date: "7 days ago", isVerified: true, stars: 5 },
  {
    date: "9 days ago",
    text: "Thank you",
    reply: "Thank you for shopping with us :)",
    isVerified: true,
    stars: 5,
  },
  {
    date: "9 days ago",
    text: "Thank you great service",
    reply: "Thanks!",
    isVerified: true,
    stars: 5,
  },
  {
    date: "17 days ago",
    text: "Works well great support",
    reply: "Appreciate it! ",
    isVerified: true,
    stars: 5,
  },
  {
    date: "17 days ago",
    text: "Works well great support",
    reply: "Thanks for shopping with us &lt;3",
    isVerified: true,
    stars: 5,
  },
  {
    date: "20 days ago",
    text: "Has a good and easy time with the account",
    reply: "Glad to hear that, thank you! ",
    isVerified: true,
    stars: 5,
  },
  { date: "23 days ago", isVerified: true, stars: 5 },
  { date: "23 days ago", isVerified: true, stars: 5 },
  {
    date: "23 days ago",
    text: "I am so grateful for the incredible service provided by this company! They went above and beyond to deliver the accounts I needed, and I couldn't be happier with the results. Thank you for your hard work and dedication!",
    reply:
      "Thank you for shopping with us! Make sure to bring your friends and family aboard so we can all start saving money in these difficult times &lt;3",
    isVerified: true,
    stars: 5,
  },
  {
    date: "25 days ago",
    text: "Just wanted to take a moment to say thanks for a great service once again! Your dedication to providing high-quality service is truly appreciated. Keep up the great work!",
    reply:
      "We appreciate your kind words. It motivates us to try even harder! &lt;3",
    isVerified: true,
    stars: 5,
  },
  {
    date: "25 days ago",
    text: "I just had to share how impressed I am with the service I received! From start to finish, everything was handled with professionalism and care. It's so refreshing to see a company that truly values their customers. Keep up the great work!",
    reply: "Thank you for your kind words it means a lot to us &lt;3",
    isVerified: true,
    stars: 5,
  },
  {
    date: "a month ago",
    text: "I was a bit skeptical, but you've removed my doubts.",
    reply: "Thank you for your trust! &lt;3",
    isVerified: true,
    stars: 5,
  },
  {
    date: "a month ago",
    text: "Fast and recommendable, good service! Thank you! ",
    isVerified: true,
    stars: 5,
  },
  {
    date: "a month ago",
    text: "The billing address for this card could not be verified. There was a problem processing your credit card. Please review and verify that the credit card information was entered correctly and that your billing address matches the address where you receive your credit card statements. Then try to place your order.” error :/ rip Hey!",
    reply:
      "Please open a ticket or reach out to us via Telegram for a faster response rate. We will issue you a replacement or offer alternative solutions that will satisfy you! &lt;3",
    isVerified: true,
    stars: 5,
  },
  {
    date: "a month ago",
    text: "No points on acct.",
    reply:
      "Hey, please open a ticket or contact us on Telegram at  T.ME/FOODNIRVANA so we can issue you a valid replacement &lt;3",
    isVerified: true,
    stars: 5,
  },
  {
    date: "a month ago",
    text: "Incorrect password to account",
    reply: "Sorry. Replacement issued &lt;3",
    isVerified: true,
    stars: 5,
  },
  {
    date: "a month ago",
    text: "Nice!! would refer my friends.",
    reply: "Thank you!— reply from Food Nirvana",
    isVerified: true,
    stars: 5,
  },
  {
    date: "a month ago",
    text: "Great experience, got what I ordered swiftly.",
    reply: "Thanks for shopping with Food Nirvana &lt;3",
    isVerified: true,
    stars: 5,
  },
  {
    date: "2 months ago",
    text: "Worked like a charm; looking forward to doing business again soon. ",
    isVerified: true,
    stars: 5,
  },
  {
    date: "2 months agoPassword incorrect. Have proof and pictures",
    isVerified: true,
    stars: 5,
  },
  { date: "2 months ago", isVerified: true, stars: 5 },
  {
    date: "3 months ago",
    text: "I love the support team I'll keep purchasing &lt;3",
    isVerified: true,
    stars: 5,
  },
  {
    date: "3 months ago",
    text: "Accounts working and has balance",
    isVerified: true,
    stars: 5,
  },
  { date: "3 months ago", isVerified: true, stars: 5 },
  { date: "3 months ago", isVerified: true, stars: 5 },
  { date: "3 months agoEASY HIT ", isVerified: true, stars: 5 },
  { date: "3 months ago", isVerified: true, stars: 5 },
  {
    date: "3 months ago",
    text: "Accounts works and has balance",
    isVerified: true,
    stars: 5,
  },
  {
    date: "3 months ago",
    text: "10/10 Got some pizza",
    isVerified: true,
    stars: 5,
  },
  {
    date: "3 months ago",
    text: "but support was great and solved the problem quickly!",
    isVerified: true,
    stars: 5,
  },
  {
    date: "3 months ago",
    text: "perfect human bean",
    isVerified: true,
    stars: 5,
  },
  {
    date: "3 months ago",
    text: "Great! Support is so very helpful!!",
    isVerified: true,
    stars: 5,
  },
  { date: "3 months ago", text: "Account works", isVerified: true, stars: 5 },
  {
    date: "3 months ago",
    text: "GREAT SUPPORT FOR THE ISSUE",
    isVerified: true,
    stars: 5,
  },
  {
    date: "3 months ago",
    text: "one of the first legit orders in a while, no problems account worked replaced when needed and support is nice and fast",
    isVerified: true,
    stars: 5,
  },
  { date: "3 months agovery easy", isVerified: true, stars: 5 },
  {
    date: "3 months ago",
    text: "I WILL NEVER STARVE WITH FOOD NIRVANA",
    isVerified: true,
    stars: 5,
  },
  { date: "3 months ago", text: "FIRE LOGSSSS", isVerified: true, stars: 5 },
  { date: "3 months ago", text: "EASY SHIT", isVerified: true, stars: 5 },
  { date: "3 months ago", text: "ALWAYS A HIT!", isVerified: true, stars: 5 },
  { date: "3 months ago", text: "GREAT SUPPORT!", isVerified: true, stars: 5 },
  { date: "3 months ago", isVerified: true, stars: 5 },
  {
    date: "3 months ago",
    text: "Worked perfectly. I will purchase another most definitely!",
    isVerified: true,
    stars: 5,
  },
  {
    date: "3 months ago",
    text: "Works as intended",
    isVerified: true,
    stars: 5,
  },
  { date: "3 months agoNo issues!", isVerified: true, stars: 5 },
  {
    date: "3 months ago",
    text: "First account had a low amount but support got it handled supper quick and got me a replacement!",
    isVerified: true,
    stars: 5,
  },
  { date: "3 months ago", text: "good", isVerified: true, stars: 5 },
  { date: "3 months ago", isVerified: true, stars: 5 },
  {
    date: "3 months ago",
    text: "Everything went smoothly. Perfect hit!",
    isVerified: true,
    stars: 5,
  },
  {
    date: "3 months ago",
    text: "ASKS FOR CVV AT CHECKOUT. WAS GIVEN 3 REPLACEMENTS, STILL DIDNT WORK. GOT FULL REFUND STORE CREDIT 💪",
    isVerified: true,
    stars: 5,
  },
  { date: "3 months ago EASY HIT, GOT HELL FOOD", isVerified: true, stars: 5 },
  {
    date: "3 months ago",
    text: "Perfect. Support helped solve the issue very promptly! They have a lifetime customer here!!",
    isVerified: true,
    stars: 5,
  },
  { date: "3 months ago", isVerified: true, stars: 5 },
  {
    date: "3 months ago",
    text: "EASY SMACK, GOT $40 WORTH OF SHIT FOR $1.99. CMON NOW 🔥",
    isVerified: true,
    stars: 5,
  },
  {
    date: "3 months ago",
    text: "ANOTHER EASY HIT. I FOLLOWED THE METHOD PROVIDED. USE CODE LENT FOR $3 OFF EACH LARGE CHEESE PIZZA.",
    isVerified: true,
    stars: 5,
  },
  {
    date: "3 months ago",
    text: "WENDYS IS THE EASIEST SHIT EVER",
    isVerified: true,
    stars: 5,
  },
  {
    date: "3 months ago",
    text: "HAD AN ISSUE, GAVE ME STORE CREDIT!!",
    isVerified: true,
    stars: 5,
  },
  {
    date: "3 months ago",
    text: "EASY SMACK. USED GOOGLE CHROME, BRAVE HAD ME AT A LOADING SCREEN WHEN I PLACED THE ORDER. DON'T BE A DUMBASS LIKE ME, MAKE SURE TO CHANGE THE NUMBER IF YOU'RE DOING DELIVERY. I STILL GOT THE SANDWICH LOLS",
    isVerified: true,
    stars: 5,
  },
  {
    date: "3 months ago",
    text: "GREAT CUSTOMER SUPPORT!! HAD AN ISSUE AND WAS GIVEN A REPLACEMENT ASAP NO ROCKY &lt;3",
    isVerified: true,
    stars: 5,
  },

  {
    date: "7 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "7 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "7 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "7 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "7 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "8 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "8 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "8 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "8 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "8 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "8 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "8 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "8 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "8 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "8 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "8 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "8 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "9 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "9 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "9 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "9 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "9 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "9 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "9 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },

  {
    date: "10 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "10 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "10 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "10 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "10 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "10 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "10 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "11 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "11 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "11 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "11 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "11 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "11 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "12 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "12 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "12 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "12 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "12 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "12 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "13 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "13 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "13 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "13 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "13 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "13 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "13 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "13 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "13 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "13 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "14 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "14 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "14 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "14 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "14 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "14 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "14 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "14 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "14 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "14 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "15 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "15 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "15 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "15 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "15 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "15 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "15 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "15 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "15 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "16 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "16 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "16 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "16 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "16 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "17 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "17 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "17 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "17 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "17 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "18 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "18 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "18 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "18 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "18 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "18 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "18 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "18 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "19 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "19 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "19 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "19 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "20 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "20 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "20 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "20 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "20 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "20 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "21 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "21 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "21 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "21 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "21 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "21 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "21 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "21 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "22 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "22 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "22 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "22 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "23 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "23 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "23 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "23 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "23 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "23 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "23 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "23 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "23 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
  {
    date: "24 days ago",
    text: "Automatic feedback after 7 days",
    isVerified: true,
    stars: 5,
  },
];

const brandCategories: { name: string; id: number }[] = [
  {
    name: "All",
    id: 0,
  },
  {
    name: "Food",
    id: 1,
  },
  {
    name: "Shopping",
    id: 2,
  },
  {
    name: "Fuel",
    id: 3,
  },
  {
    name: "Gift Cards",
    id: 4,
  },
  {
    name: "Cinema",
    id: 5,
  },
];

const faqs: QuestionInterface[] = [
  {
    question: "Will I get product instantly?",
    answer:
      "Yet, it will be instant. Cryptocurrency purchases can take a little longer, you will receive your product(-s) as soon as there are confirmations in the transaction.",
  },
  {
    question: 'How do I use "X" products?',
    answer:
      "You will receive the latest methods and instructions on how to use a product if it's said so in the description.",
  },
  { question: "Is this USA only?", answer: "Yes." },
];

const news: NewsInterface[] = [
  {
    date: "Jun 16, 2023",
    description:
      "Receiver a $5 balance reward every time you spend $50 in our store",
    more: "Join us on Telegram to not miss any announcements",
    title: "$5 reward",
  },
  {
    date: "June 16, 2023",
    more: "Check our vouches on Telegram.",
    description:
      "Every vouch picture you send, get 10% back to your store credit of what you paid for the product. Submit to @YungGoony or @Mertinjo on Telegram.",
    title: "10% cashback",
  },
  {
    date: "June, 16 2023",
    title: "Permanent 15% Discount For all crypto purchases",
    description:
      "Use code 'CRYPTO' at checkout to apply the discount and continue paying with your chosen crypto.",
    more: "Join us on telegram for daily discounts and promotions!",
  },
];

const defPaymentDetail: PaymentMethodInterface = {
  cardNumber: "",
  expiryDate: "",
  ccv: "",
};
const defCustomerDetail: CustomerDetailInterface = {
  firstName: "",
  lastName: "",
  email: "",
  country: "",
  zipCode: "",
};

export {
  defCustomerDetail,
  defPaymentDetail,
  news,
  brands,
  reviews,
  brandCategories,
  faqs,
  products,
};
