// const products = [
//     {
//         name: "wendy's",
//         picture: "",
//         price: '',
//     }
// ]

const brands = [
  {
    id: 0,
    imgSrc: "asap.jpeg",
    price: 0,
    name: "ASAP",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "bite-squad.jpeg",
    price: 0,
    name: "Bite Squad",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "cafe-rio.jpeg",
    price: 0,
    name: "Cafe Rio",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "carter's.jpeg",
    price: 0,
    name: "Carters's",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "casey's.jpeg",
    price: 0,
    name: "Casey's",
    inStock: true,
    productType: "",
  },
  {
    imgSrc: "chicken-salad-chick.jpeg",
    price: 0,
    name: "Chicken Salad Chick",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "city-brew-coffee.png",
    price: 0,
    name: "City Brew Coffee",
    inStock: true,
    productType: "gift cards",
  },
  {
    id: 0,
    imgSrc: "del-taco.jpeg",
    price: 0,
    name: "Del Taco",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "dickey's-barbeque-pit.jpeg",
    price: 0,
    name: "Dickey's Barbeque Pit",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "einstein-bros.jpeg",
    price: 0,
    name: "Einstein Bros. Bagels",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "erbert-n-gerbert's.jpeg",
    price: 0,
    name: "Erbert & Herbert's",
    inStock: true,
    productType: "gift cards",
  },
  {
    id: 0,
    imgSrc: "firehouse-subs.jpeg",
    price: 0,
    name: "Firehouse Subs",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "freddy's.jpeg",
    price: 0,
    name: "Freddy's",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "gtc.jpeg",
    price: 0,
    name: "GTC Movies",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "hot-topic.jpeg",
    price: 0,
    name: "Hot Topic",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "ihop.jpeg",
    price: 0,
    name: "IHOP",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "instacart.jpeg",
    price: 0,
    name: "Instacart",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "jane.jpeg",
    price: 0,
    name: "Jane",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "krispy-kreme.jpeg",
    price: 0,
    name: "Krispy Kreme",
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
  },
  {
    id: 0,
    imgSrc: "kum-n-go.jpeg",
    price: 0,
    name: "Kum & Go",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "loves.jpeg",
    price: 0,
    name: "Love's",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "marcus-theatres.jpeg",
    price: 0,
    name: "Marcus Theatres",
    inStock: true,
    productType: "gift cards",
  },
  {
    id: 0,
    imgSrc: "meijer.jpeg",
    price: 0,
    name: "Meijer",
    inStock: true,
    productType: "points",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "1000 Points = $1.00",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
  },
  {
    id: 0,
    imgSrc: "mountain-hike's-pizza.jpeg",
    price: 0,
    name: "Mountain Mike's Pizza",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "nando's.jpeg",
    price: 0,
    name: "Nando's PERi-PERi",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "noodles-n-company.jpeg",
    price: 0,
    name: "Noodles & Company",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "n-pizza.jpeg",
    price: 0,
    name: "&pizza",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "o'reilly-auto-parts.jpeg",
    price: 0,
    name: "O'Reilly Auto Parts",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "pilot-flying.jpeg",
    price: 0,
    name: "Pilot Flying J",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "potbelly-sandwich-shop.jpeg",
    price: 0,
    name: "Potbelly Sandwich Shop",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "pressed-juicery.jpeg",
    price: 0,
    name: "Pressed Juicery",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "restaurant.jpeg",
    price: 0,
    name: "Restaurant.com",
    inStock: true,
    productType: "gift cards",
  },
  {
    id: 0,
    imgSrc: "round-table.jpeg",
    price: 0,
    name: "Round Table Pizza",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "rubio's.jpeg",
    price: 0,
    name: "Rubio's Coastal Grill",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "safeway.jpeg",
    price: 0,
    name: "Safeway",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "salad-n-go.jpeg",
    price: 0,
    name: "Salad and Go",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "smoothie-king.jpeg",
    price: 0,
    name: "Smoothie King",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "sonic.jpeg",
    price: 0,
    name: "Sonic Drive-In",
    inStock: true,
    productType: "",
    description: ["ONE REPLACEMENT IN CASE CANCELLED / DECLINED"],
  },
  {
    id: 0,
    imgSrc: "the-human-bean.jpeg",
    price: 0,
    name: "The Human Bean",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "under-armour.jpeg",
    price: 0,
    name: "Under Armour",
    inStock: true,
    productType: "",
  },
  {
    id: 0,
    imgSrc: "wendy's.jpeg",
    price: 0,
    name: "Wendy's",
    inStock: true,
    productType: "",
    description: [
      "There is a 24-hour warranty for this product. You will not be entitled to a replacement outside the warranty.",
      "Warranty covers wrong reward balances and invalid accounts.",
      "Instructions on how to use the product will be sent to you after the purchase.",
    ],
  },
  {
    id: 0,
    imgSrc: "zaxby's.jpeg",
    price: 0,
    name: "Zaxby's",
    inStock: true,
    productType: "",
  },
];

const products = [
  {
    brandId: "",
    name: "",
    price: "",
  },
];
